main/blueprints/page/views.py
from flask import Blueprint, render_template

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home():
    return render_template('page/home.html')

main/blueprints/user/views.py
from flask import (
    Blueprint,
    redirect,
    request,
    flash,
    url_for,
    render_template)
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user)

from lib.safe_next_url import safe_next_url
from main.blueprints.user.decorators import anonymous_required
from main.blueprints.user.forms import (
    LoginForm,
    BeginPasswordResetForm,
    PasswordResetForm,
    SignupForm,
    WelcomeForm,
    UpdateCredentials)
from main.blueprints.user.models import User

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.find_by_identity(request.form.get('identity'))

        if u and u.authenticated(password=request.form.get('password')):
            if login_user(u, remember=True) and u.is_active():
                if request.headers.getlist("X-Forwarded-For"):
                    ip = request.headers.getlist("X-Forwarded-For")[0]
                else:
                    ip = request.remote_addr
                u.update_activity_tracking(ip)

                # Handle optionally redirecting to the next URL safely.
                next_url = request.form.get('next')
                if next_url:
                    return redirect(safe_next_url(next_url))

                return redirect(url_for('user.settings'))
            else:
                flash('To konto jest zablokowane.', 'error')
        else:
            flash('Login lub hasło niepoprawnę.', 'error')


    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Zostałeś wylogowany.', 'success')
    return redirect(url_for('user.login'))


@user.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordResetForm()

    if form.validate_on_submit():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash(f'Email wysłany na {u.email}.', 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Twój token wygasł.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Twoje hasło zostało zresetowane.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('user/password_reset.html', form=form)


@user.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Super, dzięki za rejestrację !', 'success')
            return redirect(url_for('user.welcome'))

    return render_template('user/signup.html', form=form)


@user.route('/welcome', methods=['GET', 'POST'])
@login_required
def welcome():
    if current_user.username:
        flash('Już wybrałeś nick.', 'warning')
        return redirect(url_for('user.settings'))

    form = WelcomeForm()

    if form.validate_on_submit():
        current_user.username = request.form.get('username')
        current_user.save()

        flash('Rejestracja zakończona, miłej pracy.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/welcome.html', form=form)


@user.route('/settings')
@login_required
def settings():
    return render_template('user/settings.html')


@user.route('/settings/update_credentials', methods=['GET', 'POST'])
@login_required
def update_credentials():
    form = UpdateCredentials(current_user, uid=current_user.id)

    if form.validate_on_submit():
        new_password = request.form.get('password', '')
        current_user.email = request.form.get('email')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()

        flash('Twoje dane zostały zapisane.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/update_credentials.html', form=form)

main/templates/layouts/app.html
{% extends 'layouts/base.html' %}

{% block header %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="d-flex flex-grow-1">
        <span class="w-100 d-lg-none d-block"><!-- hidden spacer to center brand on mobile --></span>
        <a class="navbar-brand d-inline-block" href="/">
            CHECKLISTY
        </a>

        <div class="w-100 text-right">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>



    <div class="collapse navbar-collapse flex-grow-1 text-right" id="myNavbar">
      <ul class="navbar-nav ml-auto flex-nowrap">
        {% if current_user.role == 'admin' %}
            <li>
              {% include 'admin/_menu.html' %}
            </li>
          {% endif %}
          {% if current_user.is_authenticated %}
        <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Konto
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{{ url_for('user.settings') }}">Opcję</a>
        <a class="dropdown-item" href="{{ url_for('user.logout') }}">Wyloguj</a>
      </div>
    </li>
        {% else %}
        <li class="nav-item">
                <a href="{{ url_for('user.login') }}" class="nav-link m-2 menu-item nav-active">Login</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('user.signup') }}" class="nav-link m-2 menu-item">Rejestruj</a>
            </li>
        {% endif %}
        </ul>
    </div>
</nav>
{% endblock %}

{% block footer %}

{% endblock %}

main/templates/layouts/base.html
{% import 'macros/flash.html' as flash with context %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Checklist App</title>


    <link rel="stylesheet" href="{{ url_for('static', filename='styles/vendor/fonts/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/vendor/css/bootstrap4-business.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/vendor/main.css') }}">

    <meta name="description"
          content="{% block meta_description %}{% endblock %}">

    <script src="{{ url_for('static', filename='styles/vendor/jquery1122/jquery-1.12.2.min.js') }}"></script>
    <title>{% block title %}{% endblock %}</title>

  </head>
  <body>

  {% block header %}{% endblock %}

    <main class="container">
      {{ flash.render() }}

      <div class="md-margin-top">{% block heading %}{% endblock %}</div>

      {% block body %}{% endblock %}
    </main>



    <footer class="footer text-center">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted list-inline-item">Checklist app 2020</li>
          {% block footer %}{% endblock %}
        </ul>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->


  <script src="{{ url_for('static', filename='styles/vendor/js/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='styles/vendor/js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='styles/vendor/js/moment.min.js') }}"></script>
  <script src="{{ url_for('static', filename='styles/vendor/main.js') }}"></script>
  </body>
</html>

main/templates/layouts/login.html
{% extends 'layouts/base.html' %}

{% block header %}
<!--  <a href="{{ url_for('page.home') }}">-->
<!--    <img src="{{ url_for('static', filename='images/snake-eyes-large.jpg') }}"-->
<!--         class="img-responsive center-block md-margin-bottom"-->
<!--         width="178" height="176" title="Snake Eyes" alt="Snake Eyes"/>-->
<!--  </a>-->
{% endblock %}

{% block footer %}
  <li class="list-inline-item"><a href="{{ url_for('user.signup') }}">Zarejestruj</a></li>
  <li class="list-inline-item"><a href="/">Strona Domowa</a></li>
{% endblock %}