main/blueprints/user/views.py
from flask import (
    Blueprint,
    redirect,
    request,
    flash,
    url_for,
    render_template)
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user)

from lib.safe_next_url import safe_next_url
from main.blueprints.user.decorators import anonymous_required
from main.blueprints.user.forms import (
    LoginForm,
    BeginPasswordResetForm,
    PasswordResetForm,
    SignupForm,
    WelcomeForm,
    UpdateCredentials)
from main.blueprints.user.models import User

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.find_by_identity(request.form.get('identity'))

        if u and u.authenticated(password=request.form.get('password')):
            if login_user(u, remember=True) and u.is_active():
                if request.headers.getlist("X-Forwarded-For"):
                    ip = request.headers.getlist("X-Forwarded-For")[0]
                else:
                    ip = request.remote_addr
                u.update_activity_tracking(ip)

                # Handle optionally redirecting to the next URL safely.
                next_url = request.form.get('next')
                if next_url:
                    return redirect(safe_next_url(next_url))

                return redirect(url_for('user.settings'))
            else:
                flash('To konto jest zablokowane.', 'error')
        else:
            flash('Login lub hasło niepoprawnę.', 'error')


    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Zostałeś wylogowany.', 'success')
    return redirect(url_for('user.login'))


@user.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordResetForm()

    if form.validate_on_submit():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash(f'Email wysłany na {u.email}.', 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Twój token wygasł.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Twoje hasło zostało zresetowane.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('user/password_reset.html', form=form)


@user.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Super, dzięki za rejestrację !', 'success')
            return redirect(url_for('user.welcome'))

    return render_template('user/signup.html', form=form)


@user.route('/welcome', methods=['GET', 'POST'])
@login_required
def welcome():
    if current_user.username:
        flash('Już wybrałeś nick.', 'warning')
        return redirect(url_for('user.settings'))

    form = WelcomeForm()

    if form.validate_on_submit():
        current_user.username = request.form.get('username')
        current_user.save()

        flash('Rejestracja zakończona, miłej pracy.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/welcome.html', form=form)


@user.route('/settings')
@login_required
def settings():
    return render_template('user/settings.html')


@user.route('/settings/update_credentials', methods=['GET', 'POST'])
@login_required
def update_credentials():
    form = UpdateCredentials(current_user, uid=current_user.id)

    if form.validate_on_submit():
        new_password = request.form.get('password', '')
        current_user.email = request.form.get('email')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()

        flash('Twoje dane zostały zapisane.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/update_credentials.html', form=form)

main/blueprints/user/templates/user/begin_password_reset.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Resetuj hasło{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.begin_password_reset') %}
        <legend>Zresetuj swoje hasło</legend>
        <p class="small help-block sm-margin-bottom">
          Na e-mail zostanie dostarczony link w celu restartu hasła.
        </p>

        {% call f.form_group(form.identity, css_class='sm-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Kontynuuj...
            </button>
          </div>
          <div class="col-md-6">
            <a href="{{ url_for('user.login') }}"
                class="btn btn-secondary btn-block">
              Logowanie...
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

main/blueprints/user/templates/user/login.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Zaloguj się{% endblock %}

{% block body %}
<div class="row justify-content-center align-self-center">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.login') %}
        <legend>Zaloguj się aby kontynuować</legend>

        {% call f.form_group(form.identity, css_class='sm-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Zaloguj się
            </button>


          </div>
          <div class="col-md-6">
            <a href="{{ url_for('user.begin_password_reset') }}"
               class="btn btn-secondary btn-block">
              Restartuj hasło
            </a>
        </div>
      {% endcall %}


    </div>
  </div>

{% endblock %}

main/blueprints/user/templates/user/password_reset.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Enter a new password{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.password_reset') %}
        <legend>Wpisz nowe hasło.</legend>

        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Kontynuuj
            </button>
          </div>
          <div class="col-md-6">
            <a href="{{ url_for('user.login') }}"
               class="btn btn-secondary btn-block">
              Powrót do logowania
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

main/blueprints/user/templates/user/settings.html
{% extends 'layouts/app.html' %}

{% block title %}Account settings{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-5">
      <h2>Opcję</h2>
      <h4 class="text-muted margin-bottom">{{ current_user.email }}</h4>

      <div class="list-group">
        <a href="{{ url_for('user.update_credentials') }}"
           class="list-group-item">
          Zaaktualizuj email, hasło
        </a>
        {% if current_user.username %}
          <span class="list-group-item quarter-faded text-muted">
            Twój nick to:
            <strong>{{ current_user.username }}</strong>
          </span>
        {% else %}
          <a href="{{ url_for('user.welcome') }}"
             class="list-group-item">
            Wybierz nick:
          </a>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

main/blueprints/user/templates/user/signup.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Sign up for a new account{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-5">
      <h2>Zarejestruj się.</h2>

      <div class="media md-margin-bottom">
        <div class="media-left">
          <i class="fa fa-fw fa-3x fa-bullhorn text-primary"></i>
        </div>
        <div class="media-body">
          <h4 class="media-heading">Zarejestruj nowy wzór.</h4>
          <span class="text-muted">
            Stwórz wzorcową checklistę w zależności od zadań.
          </span>
        </div>
      </div>
      <div class="media md-margin-bottom">
        <div class="media-left">
          <i class="fa fa-fw fa-3x fa-database text-primary"></i>
        </div>
        <div class="media-body">
          <h4 class="media-heading">Wykonaj checkilistę</h4>
          <span class="text-muted">
            Wykonaj codziennie checklistę, nie musisz już tworzyć nowy arkuszów w Excelu.
          </span>
        </div>
      </div>
      <div class="media md-margin-bottom">
        <div class="media-left">
          <i class="fa fa-fw fa-3x fa-trophy text-primary"></i>
        </div>
        <div class="media-body">
          <h4 class="media-heading">Raporty</h4>
          <span class="text-muted">Twórz szczegółowe raporty w fromacie xlsx.</span>
        </div>
      </div>
    </div>
    <div class="col-md-5 col-md-push-1 col-md-offset-1 well">
      {% call f.form_tag('user.signup') %}
        <legend>Rejestruj się...</legend>

        {% call f.form_group(form.email, css_class='sm-margin-bottom',
                             autofocus='autofocus',
                             placeholder='Email') %}
        {% endcall %}
        {% call f.form_group(form.name, css_class='sm-margin-bottom', placeholder='Imię') %}
        {% endcall %}
        {% call f.form_group(form.last_name, css_class='sm-margin-bottom', placeholder='Nazwisko') %}
        {% endcall %}
        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              REJESTRUJ
            </button>
          </div>
          <div class="col-md-6">
            <a href="{{ url_for('user.login') }}"
               class="btn btn-secondary btn-block">
              ZALOGUJ
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

main/blueprints/user/templates/user/update_credentials.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Update your sign in information{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.update_credentials') %}
        <legend>Aktualizuj swoje dane logowania</legend>
        <p class="small help-block sm-margin-bottom">
          Podaj aktualne hasło.
        </p>

        {% call f.form_group(form.current_password, css_class='lg-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        {% call f.form_group(form.email, css_class='sm-margin-bottom') %}
        {% endcall %}
        {% call f.form_group(form.password, css_class='sm-margin-bottom',
                             placeholder='Nowe hasło (optionalne)') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Zapisz
            </button>
          </div>
          <div class="col-md-6">
            <a href="{{ url_for('user.settings') }}"
               class="btn btn-secondary btn-block">
              Nieważne...
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

main/blueprints/user/templates/user/welcome.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Thanks for signing up{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-5">

      <p class="margin-bottom">
        Nick jest widoczny po zakońeczniu zadania w checkliście, aplikacja sprawdza czy nick jest unikalny.
      </p>

    </div>
    <div class="col-md-5 col-md-push-1 col-md-offset-1 well">
      {% call f.form_tag('user.welcome') %}
        <legend>Wybierz nick</legend>
        <p class="small help-block sm-margin-bottom">
          Możesz wybrać tylko raz.
        </p>

        {% call f.form_group(form.username, css_class='sm-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Zapisz
            </button>
          </div>

      {% endcall %}
    </div>
  </div>
{% endblock %}